import type { AnnouncementItem, Dept, LocalCity } from "./types";

export const DEPTS: Dept[] = [
  { key: "과학기술정보통신부", icon: "🛰️", desc: "ICT·AI·우주·기초연구 등 과학기술 R&D" },
  { key: "산업통상자원부", icon: "🏭", desc: "소재·부품·장비, 산업기술 인재양성" },
  { key: "중소벤처기업부", icon: "🏢", desc: "창업·중소기업 기술개발 및 투자연계" },
  { key: "다부처", icon: "🤝", desc: "2개 이상 부처 공동 추진 사업" },
  { key: "해양수산부", icon: "🌊", desc: "해양·수산·항만 분야 기술개발" },
  { key: "기후에너지환경부", icon: "🌱", desc: "기후변화·재생에너지·환경 R&D" },
  { key: "농림축산식품부", icon: "🌾", desc: "스마트팜·푸드테크 등 농식품 R&D" },
  { key: "국토교통부", icon: "🚄", desc: "스마트시티·모빌리티 국토교통 R&D" },
  { key: "보건복지부", icon: "🏥", desc: "바이오헬스·의료기기·디지털헬스" },
];

export const LOCAL_ICONS: Record<string, string> = {
  서울특별시: "🏙️",
  경기도: "🏞️",
  인천광역시: "✈️",
  대전광역시: "🔬",
  부산광역시: "🚢",
  대구광역시: "🌆",
};

const commonBody = (opts: {
  purpose: string;
  scale: string;
  target: string;
  period: string;
  detail: string[];
}) => [
  "□ 사업 목적",
  opts.purpose,
  "□ 지원 규모",
  opts.scale,
  "□ 신청 자격",
  opts.target,
  "□ 접수 기간",
  opts.period,
  "□ 세부 내용",
  ...opts.detail.map((d) => `- ${d}`),
  "※ 자세한 사항은 첨부파일 및 전문기관 홈페이지를 참고하시기 바랍니다.",
];

export const ITEMS: AnnouncementItem[] = [
  {
    ancmId: "N-2026-0142",
    ancmNo: "산업부공고 제2026-142호",
    title: "2026년 소재부품장비 기술개발사업 신규지원 대상과제 공고",
    gov: "산업통상자원부",
    dept: "산업통상자원부",
    agency: "한국산업기술기획평가원(KEIT)",
    ancmDe: "2026-07-20",
    start: "2026-07-20",
    end: "2026-08-10",
    type: "자유공모",
    irisUrl: "https://www.iris.go.kr/",
    manager: "소재부품장비팀 (042-000-0000)",
    files: [
      { name: "사업공고문.hwp", size: "312KB" },
      { name: "사업계획서 양식.hwp", size: "88KB" },
    ],
    body: commonBody({
      purpose: "소재·부품·장비 분야 공급망 자립화 및 초격차 기술 확보를 위한 연구개발 지원",
      scale: "총 48억원 내외 (과제당 최대 4억원, 2년 이내)",
      target: "중소·중견기업이 주관하고 대학·연구기관이 공동 참여하는 컨소시엄",
      period: "2026. 7. 20.(월) ~ 2026. 8. 10.(월) 18:00까지",
      detail: [
        "반도체·이차전지·디스플레이 등 4대 핵심분야 소재 국산화 기술개발",
        "주관기관은 최근 3년 이내 관련 분야 R&D 수행 이력 보유 권장",
        "협약 체결 후 즉시 사업비 집행 가능",
      ],
    }),
  },
  {
    ancmId: "N-2026-0138",
    ancmNo: "산업부공고 제2026-138호",
    title: "산업기술 인재성장 지원사업(계약학과 연계) 참여기업 모집공고",
    gov: "산업통상자원부",
    dept: "산업통상자원부",
    agency: "한국산업기술진흥원(KIAT)",
    ancmDe: "2026-07-25",
    start: "2026-07-25",
    end: "2026-08-30",
    type: "품목지정",
    irisUrl: "https://www.iris.go.kr/",
    files: [{ name: "참여기업 모집 공고문.pdf", size: "410KB" }],
    body: commonBody({
      purpose: "산업현장 맞춤형 인재 양성을 위한 대학-기업 연계 계약학과 운영 지원",
      scale: "기업당 최대 2천만원 (교육 프로그램 개발비)",
      target: "소재·부품·장비 분야 상시근로자 10인 이상 중소·중견기업",
      period: "2026. 7. 25.(토) ~ 2026. 8. 30.(일)",
      detail: ["참여 대학과 채용 연계형 계약학과 공동 운영", "재직자 재교육 과정 포함 가능"],
    }),
  },
  {
    ancmId: "N-2026-0201",
    ancmNo: "과기정통부공고 제2026-201호",
    title: "2026년 인공지능 반도체 고도화 지능형반도체 기술개발사업 공고",
    gov: "과학기술정보통신부",
    dept: "과학기술정보통신부",
    agency: "정보통신기획평가원(IITP)",
    ancmDe: "2026-07-15",
    start: "2026-07-15",
    end: "2026-08-07",
    type: "자유공모",
    irisUrl: "https://www.iris.go.kr/",
    manager: "AI반도체팀 (042-000-1111)",
    files: [
      { name: "사업안내서.pdf", size: "1.1MB" },
      { name: "제안요청서(RFP).hwp", size: "220KB" },
    ],
    body: commonBody({
      purpose: "차세대 온디바이스 AI 반도체 원천기술 확보 및 상용화 생태계 조성",
      scale: "총 320억원 (신규 과제당 연 10억원 내외, 3년)",
      target: "산·학·연 공동 컨소시엄 (주관연구개발기관 제한 없음)",
      period: "2026. 7. 15.(수) ~ 2026. 8. 7.(금) 17:00까지",
      detail: [
        "NPU 아키텍처 설계 및 저전력 구동 기술 우대",
        "특허·논문 실적을 통한 기술역량 입증 자료 필수 제출",
      ],
    }),
  },
  {
    ancmId: "N-2026-0198",
    ancmNo: "과기정통부공고 제2026-198호",
    title: "2026년 우주탐사 핵심기술개발사업 신규과제 공고",
    gov: "과학기술정보통신부",
    dept: "과학기술정보통신부",
    agency: "한국연구재단(NRF)",
    ancmDe: "2026-06-20",
    start: "2026-06-20",
    end: "2026-07-31",
    type: "지정공모",
    irisUrl: "https://www.iris.go.kr/",
    files: [{ name: "공고문.pdf", size: "540KB" }],
    body: commonBody({
      purpose: "달·소행성 탐사를 위한 핵심 원천기술 확보",
      scale: "총 150억원",
      target: "출연연·대학 주관 컨소시엄",
      period: "2026. 6. 20.(토) ~ 2026. 7. 31.(금)",
      detail: ["궤도선 통신 모듈 국산화 기술 포함", "위성항법 연계 기술 우대"],
    }),
  },
  {
    ancmId: "N-2026-0155",
    ancmNo: "중기부공고 제2026-155호",
    title: "2026년 팁스(TIPS) 기술창업 지원사업 민간투자주도형 창업지원 공고",
    gov: "중소벤처기업부",
    dept: "중소벤처기업부",
    agency: "한국엔젤투자협회",
    ancmDe: "2026-07-28",
    start: "2026-07-28",
    end: "2026-08-14",
    type: "상시공모",
    irisUrl: "https://www.iris.go.kr/",
    files: [{ name: "TIPS 창업팀 모집 공고.pdf", size: "300KB" }],
    body: commonBody({
      purpose: "민간 투자사와 정부 R&D를 연계한 유망 기술창업팀 육성",
      scale: "팀당 최대 5억원(R&D) + 엔젤투자 1억원 이상 연계",
      target: "업력 7년 이내 창업기업, TIPS 운영사 추천 필수",
      period: "2026. 7. 28.(화) ~ 2026. 8. 14.(금) 상시 접수",
      detail: ["운영사 투자 확약서 사전 확보 필요", "선정 시 후속 사업화자금 연계 가능"],
    }),
  },
  {
    ancmId: "N-2026-0149",
    ancmNo: "중기부공고 제2026-149호",
    title: "중소기업 기술혁신개발사업(디딤돌) 3차 신규과제 공고",
    gov: "중소벤처기업부",
    dept: "중소벤처기업부",
    agency: "중소기업기술정보진흥원(TIPA)",
    ancmDe: "2026-07-10",
    start: "2026-07-10",
    end: "2026-08-18",
    type: "자유공모",
    irisUrl: "https://www.iris.go.kr/",
    files: [{ name: "사업공고문.hwp", size: "290KB" }],
    body: commonBody({
      purpose: "중소기업 자체 기술개발 역량 강화를 위한 초기 단계 R&D 지원",
      scale: "과제당 최대 1.2억원(1년)",
      target: "중소기업기본법상 중소기업(창업 3년 이상 7년 미만 우대)",
      period: "2026. 7. 10.(금) ~ 2026. 8. 18.(화) 18:00까지",
      detail: ["매출액 대비 R&D 투자비율 심사 반영", "동일 과제 중복 신청 불가"],
    }),
  },
  {
    ancmId: "N-2026-0177",
    ancmNo: "다부처공고 제2026-177호",
    title: "2026년 반도체 첨단패키징 초격차 기술개발사업(다부처) 공고",
    gov: "다부처",
    dept: "다부처",
    agency: "한국산업기술기획평가원(KEIT)·정보통신기획평가원(IITP) 공동",
    ancmDe: "2026-07-05",
    start: "2026-07-05",
    end: "2026-09-15",
    type: "지정공모",
    irisUrl: "https://www.iris.go.kr/",
    files: [{ name: "다부처 공동공고문.pdf", size: "780KB" }],
    body: commonBody({
      purpose: "산업부·과기정통부 공동 추진 반도체 첨단패키징 초격차 기술 확보",
      scale: "총 620억원 (5년, 부처별 예산 분리 집행)",
      target: "산·학·연 대형 컨소시엄, 대기업 공동참여 가능",
      period: "2026. 7. 5.(일) ~ 2026. 9. 15.(화)",
      detail: ["2.5D/3D 패키징 공정기술 포함", "부처별 평가위원회 순차 심사"],
    }),
  },
  {
    ancmId: "N-2026-0162",
    ancmNo: "해수부공고 제2026-162호",
    title: "2026년 스마트 항만물류 기술개발사업 신규과제 공고",
    gov: "해양수산부",
    dept: "해양수산부",
    agency: "해양수산과학기술진흥원(KIMST)",
    ancmDe: "2026-07-18",
    start: "2026-07-18",
    end: "2026-08-25",
    type: "자유공모",
    irisUrl: "https://www.iris.go.kr/",
    files: [{ name: "사업안내서.pdf", size: "455KB" }],
    body: commonBody({
      purpose: "자율운항 하역장비 및 스마트 항만물류 통합관제 기술 개발",
      scale: "총 90억원 (과제당 최대 15억원, 3년)",
      target: "항만물류 관련 기업·연구기관 컨소시엄",
      period: "2026. 7. 18.(토) ~ 2026. 8. 25.(화)",
      detail: ["항만 내 자율주행 장비 실증 부지 연계 우대", "안전관리체계(ISM) 인증 보유 시 가점"],
    }),
  },
  {
    ancmId: "N-2026-0170",
    ancmNo: "기후에너지환경부공고 제2026-170호",
    title: "2026년 차세대 태양전지 상용화 기술개발사업 공고",
    gov: "기후에너지환경부",
    dept: "기후에너지환경부",
    agency: "한국에너지기술평가원(KETEP)",
    ancmDe: "2026-07-22",
    start: "2026-07-22",
    end: "2026-08-12",
    type: "품목지정",
    irisUrl: "https://www.iris.go.kr/",
    files: [{ name: "공고문 및 양식.zip", size: "1.4MB" }],
    body: commonBody({
      purpose: "탠덤 태양전지 등 차세대 고효율 태양광 소재·모듈 상용화 기술 확보",
      scale: "총 210억원 (과제당 연 7억원 내외, 3년)",
      target: "에너지 분야 소재기업 주관 컨소시엄",
      period: "2026. 7. 22.(수) ~ 2026. 8. 12.(수) 18:00까지",
      detail: ["효율 25% 이상 실증 데이터 보유 시 우대", "재생에너지 3020 이행계획 연계"],
    }),
  },
  {
    ancmId: "N-2026-0130",
    ancmNo: "농림부공고 제2026-130호",
    title: "스마트팜 첨단기술 국산화 기술개발사업 신규지원 공고",
    gov: "농림축산식품부",
    dept: "농림축산식품부",
    agency: "농림식품기술기획평가원(IPET)",
    ancmDe: "2026-06-25",
    start: "2026-06-25",
    end: "2026-07-25",
    type: "자유공모",
    irisUrl: "https://www.iris.go.kr/",
    files: [{ name: "사업공고문.hwp", size: "260KB" }],
    body: commonBody({
      purpose: "스마트팜 핵심 센서·제어 장비 국산화 및 데이터 표준화 기술 개발",
      scale: "총 65억원 (과제당 최대 5억원, 2년)",
      target: "농업 관련 중소기업, 스마트팜 실증농가 연계 컨소시엄",
      period: "2026. 6. 25.(목) ~ 2026. 7. 25.(토)",
      detail: ["실증농가 현장 검증 계획 포함 필수", "데이터 개방 표준(농식품 빅데이터) 연동 우대"],
    }),
  },
  {
    ancmId: "N-2026-0184",
    ancmNo: "국토부공고 제2026-184호",
    title: "2026년 자율주행·스마트시티 통합 실증사업 참여기관 공고",
    gov: "국토교통부",
    dept: "국토교통부",
    agency: "국토교통과학기술진흥원(KAIA)",
    ancmDe: "2026-07-12",
    start: "2026-07-12",
    end: "2026-08-20",
    type: "지정공모",
    irisUrl: "https://www.iris.go.kr/",
    files: [{ name: "실증사업 공고문.pdf", size: "620KB" }],
    body: commonBody({
      purpose: "자율주행 인프라와 스마트시티 데이터 플랫폼 연계 실증",
      scale: "총 180억원 (과제당 최대 20억원, 3년)",
      target: "지자체와 공동 참여 가능한 산·학·연 컨소시엄",
      period: "2026. 7. 12.(일) ~ 2026. 8. 20.(목)",
      detail: ["실증 대상 지자체 사전 협의 확인서 필요", "레벨4 자율주행 데이터 연계 우대"],
    }),
  },
];

export const LOCAL_CITIES: LocalCity[] = [
  {
    name: "서울특별시",
    source: "서울경제진흥원 R&D 지원센터",
    url: "https://seoul.rnbd.kr/",
    icon: LOCAL_ICONS["서울특별시"],
    items: [
      {
        title: "2026년 서울형 R&D 상용화 지원사업 모집공고",
        start: "2026-07-15",
        end: "2026-08-14",
        status: "접수중",
        statusKey: "open",
        agency: "서울경제진흥원",
        ancmNo: "서울-2026-054",
        posted: "2026-07-15",
        link: "https://seoul.rnbd.kr/",
        bodyType: "text",
        body: [
          "□ 사업 목적",
          "서울 소재 중소기업의 R&D 성과물 상용화 촉진 및 판로 개척 지원",
          "□ 지원 규모",
          "기업당 최대 8천만원 (매칭펀드 방식)",
          "□ 신청 자격",
          "서울시 소재 중소기업(제조업 우선)",
        ],
        images: [],
        files: [{ name: "모집공고문.pdf" }],
      },
      {
        title: "서울 바이오·의료 스타트업 기술사업화 지원사업",
        start: "2026-06-01",
        end: "2026-07-20",
        status: "마감",
        statusKey: "closed",
        agency: "서울바이오허브",
        ancmNo: "서울-2026-041",
        posted: "2026-06-01",
        link: "https://seoul.rnbd.kr/",
        bodyType: "external",
        body: [],
        images: [],
        files: [],
      },
    ],
  },
  {
    name: "경기도",
    source: "경기과학기술진흥원 G-PMS",
    url: "https://pms.gbsa.or.kr/",
    icon: LOCAL_ICONS["경기도"],
    items: [
      {
        title: "2026년 경기도 반도체 소부장 기업 기술개발 지원사업",
        start: "2026-07-20",
        end: "2026-08-11",
        status: "접수중",
        statusKey: "open",
        agency: "경기과학기술진흥원",
        ancmNo: "경기-2026-118",
        posted: "2026-07-20",
        link: "https://pms.gbsa.or.kr/",
        bodyType: "text",
        body: [
          "□ 사업 목적",
          "경기도 소재 반도체 소재·부품·장비 기업의 기술 자립화 지원",
          "□ 지원 규모",
          "기업당 최대 1.5억원",
          "□ 신청 자격",
          "경기도 소재 반도체 관련 중소·중견기업",
        ],
        images: [],
        files: [{ name: "사업공고문.hwp" }],
      },
      {
        title: "경기도 시니어 기술창업 지원사업 참여기업 모집",
        start: "2026-07-01",
        end: "2026-08-31",
        status: "접수중",
        statusKey: "open",
        agency: "경기도경제과학진흥원",
        ancmNo: "경기-2026-102",
        posted: "2026-07-01",
        link: "https://pms.gbsa.or.kr/",
        bodyType: "external",
        body: [],
        images: [],
        files: [],
      },
    ],
  },
  {
    name: "인천광역시",
    source: "인천테크노파크 IRDS",
    url: "https://irds.itp.or.kr/",
    icon: LOCAL_ICONS["인천광역시"],
    items: [
      {
        title: "2026년 인천 바이오공정 인력양성 연계 기술개발 지원사업",
        start: "2026-07-25",
        end: "2026-08-09",
        status: "마감임박",
        statusKey: "closing",
        agency: "인천테크노파크",
        ancmNo: "인천-2026-077",
        posted: "2026-07-25",
        link: "https://irds.itp.or.kr/",
        bodyType: "text",
        body: [
          "□ 사업 목적",
          "인천 송도 바이오클러스터 연계 인력양성 및 공정기술 개발",
          "□ 지원 규모",
          "과제당 최대 3억원",
        ],
        images: [],
        files: [{ name: "공고문.pdf" }],
      },
    ],
  },
  {
    name: "대전광역시",
    source: "대전일자리경제진흥원 DIPS",
    url: "https://www.dips.or.kr/",
    icon: LOCAL_ICONS["대전광역시"],
    items: [
      {
        title: "2026년 대덕특구 연계 딥테크 기술사업화 지원사업",
        start: "2026-06-10",
        end: "2026-08-07",
        status: "접수중",
        statusKey: "closing",
        agency: "대전일자리경제진흥원",
        ancmNo: "대전-2026-063",
        posted: "2026-06-10",
        link: "https://www.dips.or.kr/",
        bodyType: "pdf",
        body: [],
        images: [],
        files: [{ name: "공고문.pdf" }],
      },
      {
        title: "대전 출연연 기술이전 연계 창업기업 지원사업",
        start: "2026-05-01",
        end: "2026-06-30",
        status: "마감",
        statusKey: "closed",
        agency: "대전테크노파크",
        ancmNo: "대전-2026-048",
        posted: "2026-05-01",
        link: "https://www.dips.or.kr/",
        bodyType: "external",
        body: [],
        images: [],
        files: [],
      },
    ],
  },
  {
    name: "부산광역시",
    source: "부산테크노파크 BTIS",
    url: "https://btis.bistep.re.kr/",
    icon: LOCAL_ICONS["부산광역시"],
    items: [
      {
        title: "2026년 부산 스마트해양 기자재 기술개발 지원사업",
        start: "2026-07-14",
        end: "2026-08-28",
        status: "접수중",
        statusKey: "open",
        agency: "부산테크노파크",
        ancmNo: "부산-2026-091",
        posted: "2026-07-14",
        link: "https://btis.bistep.re.kr/",
        bodyType: "external",
        body: [],
        images: [],
        files: [],
      },
    ],
  },
  {
    name: "대구광역시",
    source: "대구경북과학기술정보서비스 DTIS",
    url: "https://www.dtis.re.kr/",
    icon: LOCAL_ICONS["대구광역시"],
    items: [
      {
        title: "2026년 대구 미래차 부품기업 전환 기술개발 지원사업",
        start: "2026-07-01",
        end: "2026-08-15",
        status: "접수중",
        statusKey: "open",
        agency: "대구테크노파크",
        ancmNo: "대구-2026-085",
        posted: "2026-07-01",
        link: "https://www.dtis.re.kr/",
        bodyType: "external",
        body: [],
        images: [],
        files: [],
      },
    ],
  },
];

export function findDept(key: string) {
  return DEPTS.find((d) => d.key === key);
}

export function findCity(name: string) {
  return LOCAL_CITIES.find((c) => c.name === name);
}
